/*******************************************************************************************************
* Class Name      	: Builder
* @description		: Interface layer - To allow other sObject builds to occur
* @author          	: Deloitte - Juan Cutrera
* Created On      	: 02/04/2025
* Modification Log	:
* -----------------------------------------------------------------------------------------------------
* Developer				Date			Modification ID		Description
* -----------------------------------------------------------------------------------------------------
* Juan Cutrera          02/04/2025		1000				Initial Version
******************************************************************************************************/
public interface Builder {

   //Skeleton method
   sObject build();
    
}